### ISSUE TITLE
orbis timesheet plugin not installing correctly

### ISSUE THREAD

**Issue by cattsit** [wp-orbis/wp-orbis-timesheets#2]
The plugin appears to be installed , but there is no Timesheets option in the WP-Admin sidebar, the [orbis_timesheets] shortcode does not work and there is no timesheets table in the database.
Any help appreciated :-)

**Comment by rvdsteege** [comment]
Orbis Timesheets is an add-on for the Orbis plugin, did you install + activate that plugin as well? It’s free to download at https://wordpress.org/plugins/orbis/. The menu item will only be shown if the Orbis plugin is activated.

**Comment by cattsit** [comment]
Thanks, I have installed Orbis first.  I have also tried a brand new (clean) install of Wordpress, then added Orbis and then the Orbis-Timesheet plug in. ;-)
All plug ins are activated - see attached 

![image](https://cloud.githubusercontent.com/assets/22159729/18464555/0e4540bc-79d5-11e6-94f6-a703bdcaf0bb.png)

**Comment by cattsit** [comment]
By the way, the Tasks plugin is also not showing up???

**Comment by rvdsteege** [comment]
Does the Orbis menu item itself show up? First item on attached screenshot.

![schermafbeelding 2016-09-13 om 09 14 15](https://cloud.githubusercontent.com/assets/10371164/18464634/77e76916-7992-11e6-897e-2f5e526c7ec2.png)

**Comment by cattsit** [comment]
Yes, and I can use the Projects, Companies and Persons.
![image](https://cloud.githubusercontent.com/assets/22159729/18464794/9aa395ee-79d6-11e6-8f82-489feb358ffb.png)

**Comment by rvdsteege** [comment]
Project, Companies and Persons are part of the Orbis plugin. It seems there's an issue in the order in which the various Orbis extensions are loaded.

Could you try using a plugin like https://nl.wordpress.org/plugins/plugins-load-order/ to make sure that the **Orbis Timesheets** and **Orbis Tasks** plugins are loaded _before_ the main Orbis plugin?

**Comment by cattsit** [comment]
Will do, I'll let you know how it goes.  Thanks very much for the prompt response.

**Comment by cattsit** [comment]
Thanks Reuel, really appreciate you help :-)
I changed the order of the plugin load and that has fixed things.
